// <auto-generated />
namespace Soundbox.Reloaded.Infrastructure.DbAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class FixDateTimeType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(FixDateTimeType));
        
        string IMigrationMetadata.Id
        {
            get { return "201511101938290_FixDateTimeType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
